- name: change owner of Redmine directory
  become: yes
  file:
    path: "{{ redmine_dir }}"
    owner: "{{ redmine_dir_owner }}"
    group: "{{ redmine_dir_group }}"
    recurse: yes

- name: check Passenger
  command:
    test -f /opt/rh/rh-ruby26/root/usr/local/bin/passenger-install-apache2-module
  register:
    result
  failed_when: result.rc not in [0, 1]
  changed_when: false

- name: install Passenger
  become: yes
  command:
    scl enable rh-ruby26 -- gem install passenger
  when: result.rc == 1

- name: install Passenger Apache module
  become: yes
  command:
    scl enable rh-ruby26 -- passenger-install-apache2-module --auto
  when: result.rc == 1

- name: get snippet for Passenger Apache module
  command:
    scl enable rh-ruby26 -- passenger-install-apache2-module --snippet
  register:
    passenger_snippet_vars
  changed_when: false

- name: create Apache configuration for Redmine
  become: yes
  template:
    src=redmine.conf
    dest=/etc/httpd/conf.d/redmine.conf

- name: restart Apache
  become: yes
  service:
    name=httpd
    state=restarted
    enabled=yes
