- name: change owner of Redmine directory
  become: yes
  file:
    path: "{{ redmine_dir }}"
    owner: "{{ redmine_dir_owner }}"
    group: "{{ redmine_dir_group }}"
    recurse: yes

- name: install Passenger
  become: yes
  gem:
    name: passenger
    user_install: no

- name: get Passenger install directory
  command:
    passenger-config --root
  register:
    passenger_root

- name: check Passenger module
  stat:
    path: "{{ passenger_root.stdout }}/buildout/apache2/mod_passenger.so"
  register:
    mod_passenger

- name: install Passenger Apache module
  become: yes
  command:
    passenger-install-apache2-module --auto
  when: not mod_passenger.stat.exists

- name: get snippet for Passenger Apache module
  command:
    passenger-install-apache2-module --snippet
  register:
    passenger_snippet_vars
  changed_when: false

- name: create Apache configuration for Redmine
  become: yes
  template:
    src: redmine.conf
    dest: "{{ apache_conf_dir }}/redmine.conf"

- name: enable Apache configuration for Redmine
  become: yes
  command:
    a2enconf redmine
  when: apache_service == 'apache2'

- name: restart Apache
  become: yes
  service:
    name: "{{ apache_service }}"
    state: restarted
    enabled: yes
