- hosts: centos
  roles:
    - system_centos
    - pg_init
    - pg
    - redmine
    - scm
    - apache
    - backup
  post_tasks:
    - name: completed
      debug:
        msg:
        - The installation has been completed.
        - "http://{{ ansible_default_ipv4.address }}{{ redmine_url_root }}"
        - "{{ redmine_protocol }}://{{ redmine_host_name }}{{ redmine_url_root }}"

- hosts: ubuntu
  roles:
    - system_ubuntu
    - pg
    - redmine
    - scm
    - apache
    - backup
  post_tasks:
    - name: completed
      debug:
        msg:
        - The installation has been completed.
        - "http://{{ ansible_default_ipv4.address }}{{ redmine_url_root }}"
        - "{{ redmine_protocol }}://{{ redmine_host_name }}{{ redmine_url_root }}"
