- hosts: redmine_servers

  roles:
    - system
    - pg
    - ruby
    - redmine
    - apache
    - scm

  post_tasks:
    - name: 完了
      debug:
        msg='インストールが完了しました。 http://{{ ansible_default_ipv4.address }}/redmine/ にアクセスしてください。'
