- name: Redmineのソースコードをチェックアウト
  become: yes
  subversion:
    repo={{ redmine_svn_url }}
    dest={{ redmine_dir }}

- name: database.ymlの作成
  become: yes
  template:
    src=database.yml
    dest={{ redmine_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: configuration.ymlの作成
  become: yes
  template:
    src=configuration.yml
    dest={{ redmine_dir }}/config/configuration.yml
    force=no

- name: Gemfile.lockが存在するか確認
  command:
    test -f {{ redmine_dir }}/Gemfile.lock
  register:
    result_test_gemfile
  failed_when: result_test_gemfile.rc not in [0, 1]
  changed_when: false

- name: gemsパッケージのインストール
  become: yes
  command:
    bundle install --path vendor/bundle
    chdir={{ redmine_dir }}
  when:
    result_test_gemfile.rc == 1

- name: gemsパッケージのアップデート
  become: yes
  command:
    bundle update
    chdir={{ redmine_dir }}
  when:
    result_test_gemfile.rc == 0

- name: secret tokenの作成
  become: yes
  command:
    bundle exec rake generate_secret_token
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- name: データベースのマイグレーション
  become: yes
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- include: settings.yml
- include: themes.yml
- include: plugins.yml

- name: restart Redmine
  become: yes
  service:
    name: httpd
    state: restarted
