- name: checkout Redmine source files
  become: yes
  subversion:
    repo: "{{ redmine_svn_url }}"
    dest: "{{ redmine_dir }}"

- name: create database.yml
  become: yes
  template:
    src: database.yml.j2
    dest: "{{ redmine_dir }}/config/database.yml"
    force: no
  register:
    result_database_yml

- name: create configuration.yml
  become: yes
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_dir }}/config/configuration.yml"
    force: no

- name: check Gemfile.lock
  command:
    test -f {{ redmine_dir }}/Gemfile.lock
  register:
    result_test_gemfile
  failed_when: result_test_gemfile.rc not in [0, 1]
  changed_when: false

- name: install Gems packages
  become: yes
  command:
    bundle install --path vendor/bundle
    chdir={{ redmine_dir }}
  when:
    result_test_gemfile.rc == 1

- name: update Gems packages
  become: yes
  command:
    bundle update
    chdir={{ redmine_dir }}
  when:
    result_test_gemfile.rc == 0

- name: create secret token
  become: yes
  command:
    bundle exec rake generate_secret_token
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- name: migrate database
  become: yes
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- name: set log rotation
  become: yes
  template:
    src: redmine.logrotate.j2
    dest: /etc/logrotate.d/redmine
    force: no

- include: plugins.yml
- include: themes.yml
- include: settings.yml
