- name: install Redmine WYSIWYG Editor plugin
  become: yes
  git:
    repo: 'https://github.com/taqueci/redmine_wysiwyg_editor.git'
    dest: "{{ redmine_dir }}/plugins/redmine_wysiwyg_editor"
    version: 0.11.0

- name: install Redmine Mail From plugin
  become: yes
  git:
    repo: 'https://github.com/taqueci/redmine_mail_from.git'
    dest: "{{ redmine_dir }}/plugins/redmine_mail_from"
    version: 2.0.0

- name: install Redmine Share plugin
  become: yes
  git:
    repo: 'https://github.com/taqueci/redmine_share.git'
    dest: "{{ redmine_dir }}/plugins/redmine_share"
    version: 1.2.0

- name: install Redmine Local Avatars plugin
  become: yes
  git:
    repo: 'https://github.com/taqueci/redmine_local_avatars.git'
    dest: "{{ redmine_dir }}/plugins/redmine_local_avatars"
    version: 1.0.5.1.0

- name: install Redmine XLSX Format Issue Exporter plugin
  become: yes
  git:
    repo: 'https://github.com/two-pack/redmine_xlsx_format_issue_exporter.git'
    dest: "{{ redmine_dir }}/plugins/redmine_xlsx_format_issue_exporter"
    version: 0.1.6

- name: install Redmine View Customize plugin
  become: yes
  git:
    repo: 'https://github.com/onozaty/redmine-view-customize.git'
    dest: "{{ redmine_dir }}/plugins/view_customize"
    version: v2.5.0

- name: install Redmine scm-creator plugin
  become: yes
  git:
    repo: 'https://github.com/taqueci/scm-creator.git'
    dest: "{{ redmine_dir }}/plugins/redmine_scm"
    version: 0.5.1.1.0

- name: install Gems
  become: yes
  command:
    scl enable rh-ruby26 -- bundle install
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- name: migrate database
  become: yes
  command:
    scl enable rh-ruby26 -- bundle exec rake redmine:plugins:migrate
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
