- name: load default data
  become: yes
  command:
    bundle exec rake redmine:load_default_data
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
    REDMINE_LANG: "{{ redmine_lang }}"
  when:
    result_database_yml is changed

- name: set display name format
  become: yes
  command:
    bundle exec rails r 'Setting["user_format"]=:lastname_firstname'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: set authentication required
  become: yes
  command:
    bundle exec rails r 'Setting["login_required"]="1"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: disable unsubscription
  become: yes
  command:
    bundle exec rails r 'Setting["unsubscribe"]="0"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: set notification conditions
  become: yes
  command:
    bundle exec rails r 'Setting["notified_events"]="---\n- issue_added\n- issue_updated\n- news_added\n- news_comment_added"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: set repository encodings
  become: yes
  command:
    bundle exec rails r 'Setting["repositories_encodings"]="UTF-8,CP932,EUC-JP"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: set commit reference keywords
  become: yes
  command:
    bundle exec rails r 'Setting["commit_ref_keywords"]="*"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: enable thumbnails
  become: yes
  command:
    bundle exec rails r 'Setting["thumbnails_enabled"]="1"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed
