- name: load default data
  become: yes
  command:
    bundle exec rake redmine:load_default_data
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
    REDMINE_LANG: "{{ redmine_lang }}"
  when:
    result_database_yml is changed

- name: set protocol
  become: yes
  command:
    bundle exec rails r "Setting['protocol']='{{ redmine_protocol }}'"
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- name: set host name
  become: yes
  command:
    bundle exec rails r "Setting['host_name']='{{ redmine_host_name }}{{ redmine_url_root }}'"
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- name: set version control systems
  become: yes
  command:
    bundle exec rails r "Setting['enabled_scm']=['Subversion','Git']"
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: set Redmine settings
  become: yes
  command:
    bundle exec rails r "Setting['{{ item.key }}']={{ item.value }}"
    chdir={{ redmine_dir }}
  with_items: "{{ redmine_settings }}"
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed
