- name: download theme PurpleMine2
  become: yes
  git:
    repo=https://github.com/taqueci/PurpleMine2.git
    dest={{ redmine_dir }}/public/themes/PurpleMine2

- name: set theme
  become: yes
  command:
    bundle exec rails r 'Setting["ui_theme"]="PurpleMine2"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed
