- name: PostgreSQL initdb
  become: yes
  command:
    postgresql-setup initdb
  register:
    result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc == 0

- name: grant access to database for Redmine
  become: yes
  lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: "{{ item.regexp }}"
    insertafter: '^# TYPE  DATABASE '
    line: "{{ item.line }}"
  with_items:
    - regexp: '^host[ \t]+redmine[ \t]+redmine[ \t]+127.0.0.1/32[ \t]+md5'
      line: 'host    redmine         redmine         127.0.0.1/32            md5'
    - regexp: '^host[ \t]+redmine[ \t]+redmine[ \t]+::1/128[ \t]+md5'
      line: 'host    redmine         redmine         ::1/128                 md5'
