- name: check SELinux
  command:
    /usr/sbin/selinuxenabled
  register:
    result
  changed_when: false
  failed_when: result.rc not in [0, 1]

- name: disable SELinux
  become: yes
  selinux: state=disabled
  when: result.rc == 0

- name: disable SELinux (setenforce)
  become: yes
  command: setenforce 0
  when: result.rc == 0

- name: check firewalld
  become: yes
  shell: firewall-cmd --state
  register: firewall_state
  ignore_errors: yes
  changed_when: false
  check_mode: no

- name: allow HTTP
  become: yes
  command: firewall-cmd --zone=public --add-service=http --permanent
  when: firewall_state.rc == 0

- name: relaod firewalld policy
  become: yes
  command: firewall-cmd --reload
  when: firewall_state.rc == 0

- name: enable extra yum repositories
  become: yes
  yum:
    name:
      - centos-release-scl
      - epel-release
    state: present

- name: install development tools
  become: yes
  yum: name='@Development Tools'

- name: install development tools for Ruby and Passenger
  become: yes
  yum:
    name='openssl-devel,readline-devel,zlib-devel,curl-devel,libyaml-devel,libffi-devel'

- name: install PostgreSQL
  become: yes
  yum:
    name='postgresql-server,postgresql-devel,python-psycopg2'

- name: install Apache
  become: yes
  yum:
    name='httpd,httpd-devel'

- name: install ImageMagick and Japanese fonts
  become: yes
  yum:
    name='ImageMagick,ImageMagick-devel,ipa-pgothic-fonts'

- name: install tools
  become: yes
  yum:
    name='subversion,git,which'

- name: make working directory
  file: path={{ work_dir }}
    state=directory
    mode=0755
