- name: make directory for Redmine.pm
  become: yes
  file:
    path: "{{ scm_perl_inc }}/Apache/Authn"
    state: directory
    mode: '0755'

- name: make symbolic link of Redmine.pm
  become: yes
  file:
    src: "{{ redmine_dir }}/extra/svn/Redmine.pm"
    dest: "{{ scm_perl_inc }}/Apache/Authn/Redmine.pm"
    state: link

- name: make directory for Subversion repository
  become: yes
  file:
    path: "{{ scm_svn_repos_path }}"
    state: directory
    mode: '0755'
    owner: "{{ redmine_dir_owner }}"
    group: "{{ redmine_dir_group }}"

- name: make directory for Git repository
  become: yes
  file:
    path: "{{ scm_git_repos_path }}"
    state: directory
    mode: '0755'
    owner: "{{ redmine_dir_owner }}"
    group: "{{ redmine_dir_group }}"

- name: set Apache configuration
  become: yes
  template:
    src: redmine_scm.conf.j2
    dest: "{{ apache_conf_dir }}/redmine_scm.conf"
    mode: '0644'

- name: enable Apache configuration for SCM
  become: yes
  command:
    a2enconf redmine_scm
  when: apache_service == 'apache2'

- name: enable Apache modules for SCM
  become: yes
  command:
    a2enmod cgi
  when: apache_service == 'apache2'

- name: set scm-creator configuration
  become: yes
  template:
    src: scm.yml.j2
    dest: "{{ redmine_dir }}/config/scm.yml"
    mode: '0755'

- name: make directory for scm-creator custom scripts
  become: yes
  file:
    path: /usr/local/libexec/redmine/scm
    state: directory
    mode: '0755'

- name: copy scm-creator custom scripts
  become: yes
  template:
    src: hook.sh.j2
    dest: /usr/local/libexec/redmine/scm/{{ item }}.sh
    mode: '0755'
  with_items:
    - pre-create
    - post-create
    - pre-delete
    - post-delete

- name: copy scm-creator script templates
  become: yes
  copy:
    src: hooks
    dest: /usr/local/libexec/redmine/scm/

- name: copy post-create script for Git
  become: yes
  copy:
    src: hooks/git/post-create.tmpl
    dest: /usr/local/libexec/redmine/scm/hooks/git/post-create
    mode: '0755'
    force: no
